# Generated by Django 6.0.6 on 2026-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitor',
            name='consecutive_successes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
