# Generated by Django 6.0.6 on 2026-06-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_monitor_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='is_currently_up',
            field=models.BooleanField(default=True),
        ),
    ]
